services:
  - type: web
    name: adaptive-deception-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "api.server:app"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FERNET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
